# Generated by Django 4.2.7 on 2023-12-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(1, 'small'), (2, 'medium'), (3, 'large'), (4, 'extra large')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'unique_together': {('size', 'price')},
            },
        ),
        migrations.CreateModel(
            name='OrderMessageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('draft', models.BooleanField(default=True)),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.crust')),
                ('topping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.topping')),
            ],
        ),
    ]
